### ISSUE TITLE
getNewResources() only returns 1 resource no matter of size

### ISSUE THREAD

**Issue by BaeFell** [nfell2009/spiget-php#1]
Seems to be a problem by Spiget.org's API itself and not the code. If a fix is released, then the code should be able to handle it fine. @InventivetalentDev

**Comment by InventivetalentDev** [comment]
Seems to be working fine for me: https://api.spiget.org/v1/resources?size=20

**Comment by BaeFell** [comment]
New resources doesn't work properly. https://api.spiget.org/v1/resources/new?size=20

EDIT:
Seems to only return 1 resource and always the same?

**Comment by InventivetalentDev** [comment]
Oh, my bad.  
Anyway, it should still be fine, there are just no more new resources since the last update.  
(It should show new ones after the next update)

**Comment by BaeFell** [comment]
Slow day... 

aaaand thankies!
